[package]
name = "eris"
version = "1.2.3"
authors = ["devs <devs@erisprotocol.com>"]
edition = "2018"
description = "Liquid staking protocol for terra classic"
license = "GPL-3.0-or-later"
repository = "https://github.com/erisprotocol/contracts-terra-classic"

[dependencies]
cosmwasm-std = { version = "1.1", features = ["stargate"] }
cw20 = "0.13.2"
schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }